### ISSUE TITLE
Propagate socketProvider.get() exception to a connection state

### ISSUE THREAD

**Issue by Joyfolk** [tarantool/tarantool-java#30]
https://github.com/tarantool/tarantool-java/blob/9eb519d5f86af3dcd8c93b89eeeb7aee659fff49/src/main/java/org/tarantool/TarantoolClientImpl.java#L107
It's better to move this line inside try/catch block.

**Comment by Totktonada** [comment]
Now we stick with this behaviour as part of the `SocketChannelProvider` contract. From README.md:

> The `TarantoolClient` will stop functioning if your implementation of a socket channel provider raises an exception or returns a null. You will need a new instance of client to recover. Hence, you should only throw in case you have met unrecoverable error.

Don't sure whether this behaviour was intentional when it was created, but it has sense for me: only logic inside `SocketChannelProvider.get()` can distinguish recoverable errors from fatal ones. TarantoolClientImpl can not do it and would retry attempts to get a socket is case of any error even if it is something unexpected.

I don't think we should change this contract. A user can wrap a `get` code with a try-catch block and perform retry in case, say, IOException, but other exceptions will lead to explicit fail (maybe we also need to provide this exception as a CommonucationException cause).

@Joyfolk Can you share your opinion on that?

**Comment by Joyfolk** [comment]
@Totktonada It is a good point about the contract. But any uncatched exception wouldn't lead to explicit fail of the application. It leads only to termination of the reconnection thread without any notification to the rest of the application and to hard-to-debug errors in the client code. I think it would be better to set connection state as dead with correct error information.

**Comment by Totktonada** [comment]
Agreed. I rephrased the issue header.

**Comment by nicktorwald** [comment]
> I think it would be better to set connection state as dead with correct error information.

@Joyfolk Please take a look at this change of the [client](https://github.com/tarantool/tarantool-java/commit/1a1dff520f61a3b26511880573972007df1e7f54#diff-12b4ba4abab12882f0d8b4824b8cf6fcR111). 
Has it already done in this commit?

**Comment by Totktonada** [comment]
Related: PR #170.

**Comment by Totktonada** [comment]
When a client is unable to connect during its creation, we have no object to call `getThumbstone()`. The exception that is raised in the case is about timeout. We should add a real cause to it: one that we got from a socket channel provider. I think the behaviour should be more or less the following:

```diff
diff --git a/src/test/java/org/tarantool/ClientReconnectIT.java b/src/test/java/org/tarantool/ClientReconnectIT.java
index f644fc8..5cb7e53 100644
--- a/src/test/java/org/tarantool/ClientReconnectIT.java
+++ b/src/test/java/org/tarantool/ClientReconnectIT.java
@@ -16,6 +16,7 @@ import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
 import org.junit.jupiter.api.function.Executable;
 
+import java.net.ConnectException;
 import java.nio.channels.SocketChannel;
 import java.time.Duration;
 import java.util.Collections;
@@ -422,4 +423,23 @@ public class ClientReconnectIT {
         return new TarantoolClientImpl(provider, makeDefaultClientConfig());
     }
 
+    @Test
+    public void testConnectionRefusedException() {
+        testHelper.stopInstance();
+
+        TarantoolClientConfig config = makeDefaultClientConfig();
+        config.initTimeoutMillis = 100;
+        CommunicationException e = assertThrows(CommunicationException.class,
+            () -> new TarantoolClientImpl(socketChannelProvider, config));
+
+        assertEquals(e.getMessage(), "100ms is exceeded when waiting " +
+            "for client initialization. You could configure init timeout " +
+            "in TarantoolConfig");
+        Throwable cause = e.getCause();
+        assertTrue(ConnectException.class.isAssignableFrom(cause.getClass()));
+        assertEquals(cause.getMessage(), "Connection refused");
+
+        testHelper.startInstance();
+    }
+
 }
```

(Maybe it is better to mock SingleSocketChannelProviderImpl or implement a socket provider that gives an error instead of starting / stopping an instance.)

Our customer recently met a connection problem and it is hard to debug it without a real cause. The only workaround now is to implement own socket channel provider and log a problem from it.

We also need to ensure (write a test) that a real cause is in thombstone when a reconnection fails after successful connect.

**Comment by Totktonada** [comment]
I think that the issue can be closed when those things will work as described above.
