### ISSUE TITLE
jdbc: map Tarantool/SQL types into JDBC/Java types

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool-java#92]
Tarantool 2.1 now support static types. Currently supported types are described on [wiki][1]. We need to map Tarantool/SQL types to JDBC types in `DatabaseMetaData.getColumns`, `ResultSetMetaData.getColumnType` and other related methods.

[1]: https://github.com/tarantool/tarantool-java/wiki/JDBC-status#data-model

**Comment by Totktonada** [comment]
`INTEGER` Tarantool/SQL type is wider then `long` Java type. We need to provide (and test) ability to set prepared statement values to, say, `2^64` and read such value from result set. A community people [says][1] a user can use setString() or setObject() to provide big integer value, so we need to support (and test) such cases. I think we also can provide more natural API with a method like setBigInteger().

[1]: https://stackoverflow.com/q/40376198

**Comment by Totktonada** [comment]
Related: #27.

**Comment by Totktonada** [comment]
See also #130 and https://github.com/tarantool/tarantool/issues/4019

**Comment by Totktonada** [comment]
Boolean was instroduced in 2.2: https://github.com/tarantool/tarantool/issues/3648

**Comment by Totktonada** [comment]
Note: A SCALAR field can hold types other then msgpack bin. We need to handle and test this appropriately.

**Comment by Totktonada** [comment]
See #209 and #210 re integer types in tarantool-2.2.

**Comment by Totktonada** [comment]
See #214 re VARBINARY type in tarantool-2.2.

**Comment by Totktonada** [comment]
We should consider the commit [2.2.0-632-g36bdfbb24](https://github.com/tarantool/tarantool/commit/36bdfbb24f00b84c2b8d1fa3231537d9f60ae298) ('sql: rename REAL/FLOAT/DOUBLE types to NUMBER') which is first released in tarantool-2.2.1. There is no good way to determine whether REAL/FLOAT/DOUBLE is supported or NUMBER. @kostja says we should drop support for tarantool versions below 2.2.1 in the scope of JDBC work. Maybe this is the only good way to handle this.

**Comment by Totktonada** [comment]
We discussed a bit the problem with floating point types. I suggest to do the following:

* Consider real/float/double as pure floating point types: as if they cannot store integral values—at least from metainfo point of view. Insert 2, select 2 should work I think. Enable tests for them on 2.1.
* Support 'number' on 2.2.1 and above. Disable float/real/double on 2.2.0 and above.
* State that all currently supported JDBC features should work since tarantool-2.2.1 in a next release notes for tarantool-java.

**Comment by Totktonada** [comment]
See also https://github.com/tarantool/tarantool/commit/b7d595ac3d92aa0977c66d935e1c6eefabb91bec

**Comment by nicktorwald** [comment]
In scope of #218 the following things were done:
1. Support BOOL / BOOLEAN type (according to tarantool/tarantool#3648)
2. Support UNSIGNED type (#210, tarantool/tarantool#4015)
3. Support INTEGER values bigger than 2^63-1 up to 2^64-1 via BigInteger (#209, tarantool/tarantool#4015)
4. Support VARBINARY type (#214, tarantool/tarantool#4206)
5. REAL/FLOAT/DOUBLE types are supported as number aliases before v2.2
6. Support NUMBER for decimal values since 2.2.1
7. Test SCALAR against different msgpack types rather than msgbin.

next issues remain:
JDBC types conversion (appendix B)

> Data Type Conversions
The recommended ResultSet getter method for each JDBC type is shown in B.6 on page B-198. This table also shows all of the possible conversions that a JDBC driver may support. The method DataBaseMetaData.supportsConvert(int fromType, int toType) returns true if the driver supports the given conversion.

It also includes ResultSet.getObject family methods, PreparedStatement.setObject family methods, and implicit conversions between types defined in Appendix B.

**Comment by Totktonada** [comment]
Nice! I think we can close this issue with PR #218 and file a new one about type conversions.

**Comment by nicktorwald** [comment]
done in commit 2cc1a091e82df8969201bed1b81c993a8e917a87
